// src/utils/sanitizeRules.ts
import type { SanitizeMap } from "./sanitize";

export const sanitizeRules: SanitizeMap = {
  User: {
    // YALNIZCA bunları bırak (password/role otomatik gelmez)
    include: ["id", "name", "email"],
  },

  Company: {
    include: ["id", "name", "code"],
  },

  CompanyProject: {
    include: ["id", "code", "name", "company","createdBy","updatedBy"],
    relations: {
      company: "Company",
      createdBy: "User",
      updatedBy: "User",
    },
  },

  CompanyStock: {
    include: [
      "id",
      "code",
      "name",
      "category",
      "description",
      "unit",
      "quantity",
      "minimumQuantity",
      "location",
      "stockDate",
      "project",
      "company",
      "createdBy",
      "updatedBy",
      "createdatetime",
      "updatedatetime",
    ],
    relations: {
      company: "Company",
      project: "CompanyProject",
      createdBy: "User",
      updatedBy: "User",
    },
  },

  CompanyBalance: {
    include: [
      "id",
      "code",
      "name",
      "amount",
      "currency",
      "createdatetime",
      "updatedatetime",
    ],
  },

  CompanyLoan: {
    include: [
      "id",
      "code",
      "name",
      "bank",
      "accountNo",
      "totalAmount",
      "remainingPrincipal",
      "remainingInstallmentAmount",
      "currency",
      "interestRate",
      "totalInstallmentCount",
      "remainingInstallmentCount",
      "loanDate",
      "purpose",
      "loanType",
      "status",
      "description",
      "createdBy",
      "updatedBy",
      "project",
      "company",
      "createdatetime",
      "updatedatetime",
    ],
    relations: {
      company: "Company",
      bank: "CompanyBalance",
      project: "CompanyProject",
      createdBy: "User",
      updatedBy: "User",
    },
  },

  CompanyLoanPayment: {
    include: [
      "id",
      "code",
      "installmentNumber",
      "dueDate",
      "totalAmount",
      "interestAmount",
      "principalAmount",
      "paymentAmount",
      "remainingAmount",
      "penaltyAmount",
      "status",
      "paymentDate",
      "createdatetime",
      "updatedatetime",
      "loan",
      "createdBy",
      "updatedBy",
    ],
    relations: {
      loan: {
        include: ["id", "code", "name"], // <— sadece name gelecek
      },
      createdBy: "User",
      updatedBy: "User",
    },
  },

  CompanyOrder: {
    include: [
      "id",
      "code",
      "customerName",
      "totalAmount",
      "receivedAmount",
      "remainingAmount",
      "status",
      "description",
      "stockType",
      "createdatetime",
      "updatedatetime",
      "project",
      "stock",
      "company",
      "createdBy",
      "updatedBy",
    ],
    relations: {
      project: "CompanyProject",
      stock: "CompanyStock",
      company: "Company",
      createdBy: "User",
      updatedBy: "User",
    },
  },

  ProjectSubcontractor: {
    include: [
      "id",
      "code",
      "companyName",
      "category",
      "description",
      "unit",
      "unitPrice",
      "quantity",
      "contractAmount",
      "paidamount",
      "remainingAmount",
      "status",
      "addedFromQuantityYN",
      "locked",
      "projectQuantity",
      "createdatetime",
      "updatedatetime",
      "createdBy",
      "updatedBy",
      "project",
      "company",
    ],
    relations: {
      company: "Company",
      projectQuantity: "ProjectQuantity",
      project: "CompanyProject",
      createdBy: "User",
      updatedBy: "User",
    },
  },

  ProjectSupplier: {
    include: [
      "id",
      "code",
      "companyName",
      "category",
      "description",
      "unit",
      "unitPrice",
      "quantity",
      "contractAmount",
      "paidAmount",
      "remainingAmount",
      "status",
      "addedFromQuantityYN",
      "locked",
      "projectQuantity",
      "createdatetime",
      "updatedatetime",
      "createdBy",
      "updatedBy",
      "project",
      "company",
      //"quantityItem"
    ],
    relations: {
      company: "Company",
      projectQuantity: "ProjectQuantity",
      project: "CompanyProject",
      createdBy: "User",
      updatedBy: "User",
    },
  },

  CompanyCheck: {
    include: [
      "id",
      "code",
      "checkDate",
      "transactionDate",
      "dueDate",
      "firm",
      "amount",
      "checkNo",
      "description",
      "status",
      "type",
      "status",
      "bank",
      "processedAmount",
      "remainingAmount",
      "project",
      "company",
      "createdBy",
      "updatedBy",
      "createdatetime",
      "updatedatetime",
      //"quantityItem"
    ],
    relations: {
      company: "Company",
      bank: "CompanyBalance",
      project: "CompanyProject",
      createdBy: "User",
      updatedBy: "User",
    },
  },

  CompanyBarterAgreement: {
    include: [
      "id",
      "code",
      "company",
      "project",
      "counterpartyType",
      "counterpartyId",
      "counterpartyName",
      "agreementDate",
      "status",
      "description",
      "totalOurValue",
      "totalTheirValue",
      "createdBy",
      "updatedBy",
      "createdatetime",
      "updatedatetime",
    ],
    relations: {
      company: "Company",
      project: "CompanyProject",
      createdBy: "User",
      updatedBy: "User",
    },
  },

  CompanyBarterAgreementItem: {
    include: [
      "id",
      "code",
      "company",
      "barterAgreement",
      "direction",
      "itemType",
      "description",
      "agreedValue",
      "processedAmount",
      "remainingAmount",
      "status",
      "relatedStock",
      "relatedSubcontractor",
      "relatedSupplier",
      "assetDetails",
      "createdBy",
      "updatedBy",
      "createdatetime",
      "updatedatetime",
    ],
    relations: {
      company: "Company",
      barterAgreement: "barterAgreement",
      relatedStock: "relatedStock",
      relatedSubcontractor: "relatedSubcontractor",
      relatedSupplier: "relatedSupplier",
      createdBy: "User",
      updatedBy: "User",
    },
  },

  CompanyEmployee: {
    include: [
      "id",
      "code",
      "firstName",
      "lastName",
      "age",
      "startDate",
      "netSalary",
      "grossSalary",
      "position",
      "department",
      "paidLeaveAmount",
      "sickLeaveAmount",
      "roadLeaveAmount",
      "excuseLeaveAmount",
      "company",
      "employeeProjects",
      "createdBy",
      "updatedBy",
      "createdatetime",
      "updatedatetime",
    ],
    relations: {
      company: "Company",
      createdBy: "User",
      updatedBy: "User",
      employeeProjects: "employeeProjects",
    },
  },

  CompanyEmployeeLeave: {
    include: [
      "id",
      "employee",
      "company",
      "startDate",
      "endDate",
      "leaveDayCount",
      "type",
      "description",
      "createdBy",
      "updatedBy",
      "createdatetime",
      "updatedatetime",
    ],
    relations: {
      company: "Company",
      createdBy: "User",
      updatedBy: "User",
      employee: "employee",
    },
  },

  CompanyFinance: {
    include: [
      "id",
      "code",
      "company",
      "type",
      "amount",
      "currency",
      "fromAccount",
      "toAccount",
      "targetType",
      "targetId",
      "targetName",
      "transactionDate",
      "method",
      "category",
      "invoiceYN",
      "invoiceCode",
      "description",
      "source",
      "referenceCode",
      "project",
      "check",
      "order",
      "loanPayment",
      "subcontractor",
      "supplier",
      "barterItem",
      "createdBy",
      "updatedBy",
      "createdatetime",
      "updatedatetime",
    ],
    relations: {
      company: "Company",
      createdBy: "User",
      updatedBy: "User",
      project: "project",
      check: "check",
      order: "order",
      loanPayment: "loanPayment",
      subcontractor: "subcontractor",
      supplier: "supplier",
      barterItem: "barterItem",
      fromAccount: "fromAccount",
      toAccount: "toAccount",
    },
  },

ProjectQuantity: {
    include: [
      "id",
      "code",
      "company",
      "project",
      "quantityItem",
      "quantity",
      "unit",
      "description",
      "category",
      "createdBy",
      "updatedBy",
      "createdatetime",
      "updatedatetime",
    ],
    relations: {
      company: "Company",
      createdBy: "User",
      updatedBy: "User",
      project: "project",
    },
  },
};
